export type Company = {
    id: number,
    created_at: Date,
    updated_at: Date,
    user_id: number,
    location: string,
    description: string,
    company_name: string,
    company_logo: string,
    company_size: string,
    phone: string,
    email: string,
    facebook_link: string,
    twitter_link: string,
    google_plus_link: string,
    linkedin_link: string,
    website: string,
    complete_address: string,
    est_since: string,
    primary_industry: string,
}