export type User = {
    id: number,
    created_at: Date,
    updated_at: Date,
    bio: string,
    avatar: string,
    email: string,
    phone: string,
    company_id: number,
    resume: string,
    status: "active" | "deactivated",
    user_type: "candidate" | "employer",
    name: string,
    website: string,
    current_salary: string,
    expected_salary: string,
    age: number,
    experience: string,
    linkedin_link: string,
    github_link: string,
    twitter_link: string,
    facebook_link: string,
}